### ISSUE TITLE
Revit crashes when second document is created/opened and DockableDialog is used 

### ISSUE THREAD

**Issue by nikolovinn** [jeremytammik/DockableDialog#1]
Dear Jeremy,

I use your example of Dockable Window. However, lately, I figured out an error appearing. It is appearing when the plugin is installed, even without opening the Dockable window. I also tested with your example in Github and the error appears again. The issue can be reproduced when you install the plugin. The open a first empty document. Now everything is ok. But when you create a second empty document Revit crashes. The error that is appearing is the following:

An unrecoverable error has occurred. The program will now be
terminated. All of your data has been recently saved, so there is no
need to create recover files.

I experience this issue on Revit 2017 and 2018. I did not test on other versions.

Could you please share if you know any possible reasons and solution?

Thank you in advance!

**Comment by jeremytammik** [comment]
i am not aware of the problem nor any solution. please do share it once you nail it down. thank you!

**Comment by jeremytammik** [comment]
i suggest you raise this issue with a larger audience in the Revit API discussion forum at http://forums.autodesk.com/t5/revit-api/bd-p/160

**Comment by jeremytammik** [comment]
oh, i see you already did. good for you!

**Comment by jeremytammik** [comment]
For others, here it is: Revit crashes when second document is created/opened and DockableDialog is used ...
https://forums.autodesk.com/t5/revit-api-forum/revit-crashes-when-second-document-is-created-opened-and/td-p/7746003
